services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/publications
    env_file:
      - '.env.test.local'
      - '.env.local'
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
